[aws]
format = '| [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = "aws:"

[buf]
format = '(| [$symbol($version )]($style))'

[bun]
format = '(| [$symbol($version )]($style))'

[c]
format = '(| [$symbol($version(-$name) )]($style))'

[cpp]
format = '(| [$symbol($version(-$name) )]($style))'

[cmake]
format = '(| [$symbol($version )]($style))'

[cobol]
format = '(| [$symbol($version )]($style))'

[crystal]
format = '(| [$symbol($version )]($style))'

[daml]
format = '(| [$symbol($version )]($style))'

[dart]
format = '(| [$symbol($version )]($style))'

[deno]
format = '(| [$symbol($version )]($style))'

[docker_context]
disabled = true

[dotnet]
format = '(| [$symbol($version )(ðŸŽ¯ $tfm )]($style))'

[elixir]
format = '(| [$symbol($version \(OTP $otp_version\) )]($style))'

[elm]
format = '(| [$symbol($version )]($style))'

[erlang]
format = '(| [$symbol($version )]($style))'

[fennel]
format = '(| [$symbol($version )]($style))'

[gleam]
format = '(| [$symbol($version )]($style))'

[golang]
format = '(| [$symbol($version )]($style))'

[haskell]
format = '(| [$symbol($version )]($style))'

[helm]
format = '(| [$symbol($version )]($style))'

[java]
format = '(| [$symbol($version )]($style))'

[julia]
format = '(| [$symbol($version )]($style))'

[kotlin]
format = '(| [$symbol($version )]($style))'

[lua]
format = '(| [$symbol($version )]($style))'

[nim]
format = '(| [$symbol($version )]($style))'

[nodejs]
format = '(| [$symbol($version )]($style))'

[ocaml]
format = '(| [$symbol($version )(\($switch_indicator$switch_name\) )]($style))'

[opa]
format = '(| [$symbol($version )]($style))'

[package]
format = '(is [$symbol$version]($style) )'
disabled = true

[perl]
format = '(| [$symbol($version )]($style))'

[php]
format = '(| [$symbol($version )]($style))'

[purescript]
format = '(| [$symbol($version )]($style))'

[python]
format = '(| [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style))'

[quarto]
format = '(| [$symbol($version )]($style))'

[raku]
format = '(| [$symbol($version-$vm_version )]($style))'

[red]
format = '(| [$symbol($version )]($style))'

[rlang]
format = '(| [$symbol($version )]($style))'

[ruby]
format = '(| [$symbol($version )]($style))'

[rust]
format = '(| [$symbol($version )]($style))'

[scala]
format = '(| [$symbol($version )]($style))'

[swift]
format = '(| [$symbol($version )]($style))'

[typst]
format = '(| [$symbol($version )]($style))'

[vagrant]
format = '(| [$symbol($version )]($style))'

[vlang]
format = '(| [$symbol($version )]($style))'

[zig]
format = '(| [$symbol($version )]($style))'
